# Quickfind section

In [1]:
from quickfind import WeightedQuickUF

a = WeightedQuickUF(n=15)

# make one section with 4 elements
a.union(0,3)
a.union(0,4)
a.union(0,9)

# make another section with 3 elements
a.union(12,13)
a.union(12,14)

a.ids

[3, 1, 2, 3, 3, 5, 6, 7, 8, 3, 10, 11, 13, 13, 13]

In [2]:
a.union(12,9)
a.ids

[3, 1, 2, 3, 3, 5, 6, 7, 8, 3, 10, 11, 13, 3, 13]

In [3]:
a.union(10,13)
a.ids

[3, 1, 2, 3, 3, 5, 6, 7, 8, 3, 3, 11, 13, 3, 13]

In [4]:
a.find(12)
a.ids

[3, 1, 2, 3, 3, 5, 6, 7, 8, 3, 3, 11, 3, 3, 13]

In [5]:
print(a.count())
a.ids

8


[3, 1, 2, 3, 3, 5, 6, 7, 8, 3, 3, 11, 3, 3, 3]

# Percolation section

In [6]:
from percolation import Percolation
a = Percolation(N=3)

import numpy as np
np.array(a.check()).reshape((3,3))

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [7]:
a.Open(2,2)
a.Open(1,2)
print(a.percolates())
np.array(a.check()).reshape((3,3))

False


array([[False,  True, False],
       [False,  True, False],
       [False, False, False]])

In [8]:
a.Open(3,3)
a.Open(2,3)
print(a.percolates())
np.array(a.check()).reshape((3,3))

True


array([[False,  True, False],
       [False,  True,  True],
       [False, False,  True]])